import React, {Fragment} from "react";
import Head from "next/head";
import Player from "../../components/player/Player";

const PlayerPage = () => {
  return <Fragment>
    <Head>
        <title>MiniTube: Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon shorticon" href="/mt3.ico" />
    </Head>
    <Player/>
    
  </Fragment>;
};

export default PlayerPage;
