import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import LandingPage from "../components/landing/LandingPage";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>MiniTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon shorticon" href="/mt3.ico" />
      </Head>

      <LandingPage />
    </Fragment>
  );
}
